/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public static void main(String arg[]) {
    	System.out.println("When there is fire, commit and Push.");
    	System.out.println("When there is fire, this is Yankees.");
    	
    	System.out.println("When there is fire, commit and Push.");
        System.out.println("This is REDSOX");
    }
    
    public boolean someLibraryMethod() {
    	return true;
    }
}
